# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1.66.0
        with:
          ruby-version: '2.6'

      # Runs a single command using the runners shell
      - name: install asciidoctor
        run: gem install asciidoctor

      # Runs a set of commands using the runners shell
      - name: Print asciidoctor version
        run: |
          cd docs/
          asciidoctor index.adoc

      - name: copy to gh-pages
        run: cp docs/index.html gh-pages/
        
      - name: Commit to gh-pages
        working-directory: ./gh-pages
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update documentation."
          git push

